### ISSUE TITLE
Transaction notification not working correctly.

### ISSUE THREAD

**Issue by farscapian** [clams-tech/browser-app#71]
When performing the worlds first economic transaction between two clams wallets, the receiver wallet did not properly signal to the user that the transaction had settled. Inspecting the Lightning node revealed that the Lightning transaction went through, but that fact was NOT reflected in the Clams wallet interface.

Note, this issue MAY BE related to Issue https://github.com/clams-tech/browser-app/issues/70 since it was on the same node having issues over there.

**Comment by aaronbarnardsound** [comment]
Looks like this was due to a rune permissions issue (as seen in [this error notification](https://github.com/clams-tech/browser-app/issues/70#issuecomment-1369949749)) due to our docs being incorrect and not including the `waitanyinvoice` method in the documented command. Docs have been updated and the new command for generating a rune that allows for listening to payment updates can be found [here](https://docs.clams.tech/authentication/#lightning-payments).
